### PR TITLE
Add WindSE Schema File

### PR DESCRIPTION
**Pull request by eyoung55**

### CODE REVIEW

**Comment by rafmudaf** [comment]
Just a heads up that I added a simple documentation page for the schema: https://rafmudaf.github.io/WETOStack/attributes_schema.html

**Comment by rafmudaf** [comment]
What do you think about a field for physics level of fidelity? For example, for OpenFAST:

```yaml
governing_equations:
- actuator line method
- blade element momentum theory
- etc
model_fidelity:
- mid
```

**Comment by rafmudaf** [comment]
Thanks for the great input @eyoung55!

**Comment by eyoung55** [comment]
I missed the `schema_doc` update, thanks for the clean up! This whole approach looks good, easy to understand, esp with the schema/template to build off.

**Pull request merged**
